### ISSUE TITLE
Mac OS and packetflix URL

### ISSUE THREAD

**Issue by hellt** [siemens/cshargextcap#14]
Hi all,
thanks for this great service, this looks like an amazing companion to Containerlab.

I was trying to make the Wireshark plugin to work with Edgeshark UI on mac os.
I am successfully using the Edgeshark UI, but I think some installation step is missing for Mac OS installation when it comes to the csharg plugin.

I copied it over to the extcap dir of my wireshark installation, but it feels like something needs to be added on mac to intercept the packetfix:// url schema and open wireshark, because nothing happens when I click on the "fin" in the Edgeshark UI. Using Chrome browser.

ADD1: when I copy/paste the packetfix:// link and paste in the packetfix capture option in the Wireshark UI it all works correctly.
So it is only the matter of opening up the wireshark when I this link is opened by the browser.

Thanks!

**Comment by thediveo** [comment]
We were afraid that this would come up 😁 

For myself, I lack the needed macOS knowledge to write an installer and additionally register the needed capture URL handler. I didn't find a colleague having the knowledge and wanting to contribute, so we're at this point reliant on other devs contributing. I'm willing to test though, as I have snatched up an old Intel macbook (that is perfectly fine BTW).

**Comment by hellt** [comment]
gotcha, thanks @thediveo 
Edgeshark is too good to let it go and I see thousands of happy network engineers using this in various scenarios.

Not a macos dev myself either, but this should be still accurate and working -- https://www.802101.com/wireshark-integration-with-unetlab-on-osx/

**Comment by hellt** [comment]
I used Apple Script Editor to open the script

here is its contents

```
on open location this_URL
	set get_date to do shell script "date +%Y%m%d-%H%M%S"
	set cap_URL to this_URL
	set new_cap_HOST to word 2 of cap_URL
	set new_cap_INT to word 3 of cap_URL
	set capturefile to new_cap_INT & "-" & text 1 thru 15 of get_date
	# set cap_out to capture.new_cap_INT
	# display dialog new_cap_HOST
	# display dialog new_cap_INT
	tell application "Terminal"
		activate
		do script "mkfifo /tmp/" & capturefile
		do script "wireshark -k -i /tmp/" & capturefile
		do script "ssh root@" & new_cap_HOST & " tcpdump -U -i " & new_cap_INT & " -s 0 -w - > /tmp/" & capturefile
	end tell
end open location
```

Now I think all I need is to pass the URL to the wireshark app, without any of that extra bits that save the pcap

**Comment by thediveo** [comment]
I'm wondering if the tell can target Wireshark instead of the Terminal wrapper? On Linux, the [desktop file](https://github.com/siemens/cshargextcap/blob/83e731d2d98e9abe6046487f321f7af156abccde/packaging/linux/com.github.siemens.packetflix.desktop#L10C6-L10C60) boils down to:

```ini
Exec=wireshark -k -i packetflix -o extcap.packetflix.url:%u
```

...where `%u` is the URL passed to the invokation.

**Comment by hellt** [comment]
@thediveo yeah, I have almost finished fixing this plugin.
hopefully share this with you today

**Comment by hellt** [comment]
@thediveo do you mind giving it a try?
"works on my machine", but it would be great if more people give it a try

[edgeshark-handler.zip](https://github.com/siemens/cshargextcap/files/14195661/edgeshark-handler.zip)

When unarchived you will find an applescript program title edgeshark-handler
move it to `Applications` on mac.

Then try using the FIN in the web UI. The prompt should appear
<img width="656" alt="image" src="https://github.com/siemens/cshargextcap/assets/5679861/94710bea-169c-46eb-8677-00aaf52fd4d9">


Maybe another prompt will appear saying that it is not wise to run scripts downloaded from the internet, in that case you need to go to global Settings -> Privacy And Security and under the Security section there will be a prompt to allow the script to run (not shown on the screenshot below)

<img width="728" alt="image" src="https://github.com/siemens/cshargextcap/assets/5679861/c7ee9bec-f837-4e85-9fef-d52da9161caa">

**Comment by hellt** [comment]
I did a quick test with a colleague and it worked nicely.
Will do some docs around this on https://containerlab.dev and share with you

**Comment by thediveo** [comment]
Will try tomorrow when in office.

There's a nice story behind your contribution you can'tyet be aware of: we originally started years back using GNS3 with its absolutely fresh beta Docker support, and that brought me into container networking, giving eventually birth to Edgeshark. Now things circle back to using Edgeshark for containers for network simulation in form of Containerlab.

**Comment by hellt** [comment]
> Will try tomorrow when in office.
> 
> There's a nice story behind your contribution you can'tyet be aware of: we originally started years back using GNS3 with its absolutely fresh beta Docker support, and that brought me into container networking, giving eventually birth to Edgeshark. Now things circle back to using Edgeshark for containers for network simulation in form of Containerlab.

right, we are in the regular networking domain dreamt of a web UI for wireshark in one form or the other. Edgeshark is something that crosses off 80% from my wishlist.

I'll make sure to praise your work soon in social media. Stellar work!

**Comment by thediveo** [comment]
It'll raise a good chuckle when I report that we're getting praise from hell(t). So we need to repent, either or both on our tooling and/or container technology.

**Comment by hellt** [comment]
I am not, I saw it being mentioned in the docs though, but haven't checked this.

I wonder if it is feasible at all to raise UI/UX enhancements to the edgeshark or is it more or less a "finished" project and not something that is actively developed now?

**Comment by thediveo** [comment]
we open sourced it so that there can be community contributions.

**Comment by thediveo** [comment]
Let's discuss the ui/ux then separately. I wonder if in your case a network topology view helps at all, especially I wondered on many a hike in the landscape how filtering would even work. Maybe yours might be a list/tabular view, or even just simple cards, that you can filter...?

**Comment by hellt** [comment]
@thediveo let me know how you want to carve out the ui/x discussion thread. In a separate GH issue, or maybe email thread, or a call, or over the beers :D

**Comment by thediveo** [comment]
I've started analyzing the URL handler app, but I hit a problem here: the binary blobs included in it. Looks like it is not really easy to generate them, but I cannot simply check-in binary blobs nor distribute them without knowing exactly how we created them in the first place.

**Comment by thediveo** [comment]
Ah, I've been able to create anew using Apple's Script Editor.

**Comment by thediveo** [comment]
Finally got it recreated anew using Apple's Script Editor, and also added the Edgeshark icon to the package. Will now work on updated documentation with installation instructions.

**Comment by hellt** [comment]
Here is my testimonial https://www.linkedin.com/feed/update/urn:li:activity:7161328352350330880

**Comment by thediveo** [comment]
Thank you very much! And your work has helped so much to get the missing URL scheme handler in place. I'm now updating everything accordingly.

As for the ux/ui discussion, I would recommend creating a new discussion https://github.com/siemens/edgeshark/discussions, the ideas category seems to be fitting. I wonder if you might even have more fun with Grafana dashboards and we bring the shark fin button to it...?

**Comment by hellt** [comment]
> As for the ux/ui discussion, I would recommend creating a new discussion https://github.com/siemens/edgeshark/discussions, t

https://github.com/siemens/edgeshark/discussions/42

**Comment by hellt** [comment]
I'd be super interested to see what it takes to bring this up to a k8s cluster

**Comment by thediveo** [comment]
ach, we actually have full k8s support with a central cluster-wide frontend service; however, this is only company-internal at this time. I don't know if this can be open-sourced.

alas, I've a packet-handler.app/.zip now working with the instruction; it took me several botched attempts to finally figure out that after downloading the zip, its quarantaine attribute needs to be removed. Otherwise, macos will block and claim that "it's broken".

**Comment by hellt** [comment]
> ach, we actually have full k8s support with a central cluster-wide frontend service; however, this is only company-internal at this time. I don't know if this can be open-sourced.

ah, I thought it is a matter of shoveling in some daemonsets and some flags to the gostwire/packetflix... 
Alright, maybe I will challenge cilium to hack this in the CNI ;)

**Comment by thediveo** [comment]
The demonset is one part, and you can get already away with that. We have a central front-end service that tracks the demonset instances and automatically collects and aggregates the information about the available capture targets, so that the extcap plugin gets a unified cluster-wide view without having to know on which node a pod is running.

**Comment by hellt** [comment]
yeah, sounds like what the industry needs exactly.
Maybe one day you will let it fly in the open
