### ISSUE TITLE
Wireshark : There is no device named "packetflix" 

### ISSUE THREAD

**Issue by vPackets** [siemens/cshargextcap#17]
Hi guys !

First of all , thanks for this awesomeness piece of code !
I followed the instructions on my Mac M1 Pro:

- Downloaded cshargextcap_0.10.6_linux_arm64.tar.gz, unzipped it and coppied over /Applications/Wireshark.app/Contents/MacOS/extcap
-
    download the packetflix-handler.zip archive.
    run the CLI command xattr -d com.apple.quarantine packetflix-handler.zip.
    unpack packetflix-handler.zip by double clicking it in Finder.
    copy packetflix-handler(.app) to your Applications folder, /Applications.
    go to "System Preferences" > "Security and Privacy" > tab "General" or "Security" section. Allow the packetflix-handler. In case you don't see anything here, try to start a capture from the web UI first, and as this will be blocked, you should now see here a notice with a button to enable the packetflix-handler.

When I launch a capture using the GUI, Packetflix-handler launch with Wireshark.

Wireshark immediately popup with an error message saying that the packetflix device does not exists 

I tried to launch Wireshark natively and still no sign of this packetflix or ghostwire device.

Thanks a ton !

**Comment by thediveo** [comment]
It took me a while to spot, so in case this is not a typing error, then you seem to have downloaded the _Linux_ binary instead of the _macos_ version. The error message would fit in, as it indicates that Wireshark cannot load the extcap binary. If this is the case, can you please give it a try with the arm64 macos package?

**Comment by vPackets** [comment]
Rofl ! you are right ! I feel bad about it ! :) It works flawlessly ! what you guys did is awesome !

**Comment by thediveo** [comment]
No need to feel bad, you're in good company! Thank you for the details that were really instrumental here, and glad to hear you're a happy camper.
