### ISSUE TITLE
Feature Request: Add this to AUR packages

### ISSUE THREAD

**Issue by Emporea** [siemens/cshargextcap#3]
It would be quite useful to add this plugin to arch aur packages for easier deployment.

**Comment by thediveo** [comment]
After some research (such as how to potentially test this in an Arch Docker container, etc.) this looks like a more involved issue, so we would be really thankful to get help here. Ideally, a PR would be great! Things that worry me are, for instance, that we need to build a large base first with Wireshark and the XDG URL scheme handler tools before we can build the plugin and test its correct installation.

**Comment by thediveo** [comment]
provided on main now; please see the installation section of the README for instructions on how to install on Arch. Thank you very much for your input!

**Comment by napaalm** [comment]
@thediveo would it be possible to upload the PKGBUILD to [aur.archlinux.org](https://aur.archlinux.org)? This would allow for automatic updates when using an AUR helper (i.e. `yay -Syu`).
See also the [AUR submission guidelines](https://wiki.archlinux.org/title/AUR_submission_guidelines). It's a very straightforward process.
